-- A refresh token allows an account to stay logged in on a device forever.
-- They do this by allowing an API client to keep asking for new access tokens
-- which are shorter lived. Refresh tokens may be revoked for security
-- considerations whereas short lived access tokens may not be revoked.
--
-- See the [Auth0 blog][1] for more information about refresh tokens.
--
-- [1]: https://auth0.com/learn/refresh-tokens
CREATE TABLE refresh_token (
  -- We use a UUID to identify our refresh tokens. The UUID is generated by
  -- our application server instead of our database.
  token UUID PRIMARY KEY,
  -- The account that this refresh token is tied to. When refreshing an access
  -- token we will use this account ID for the new access token.
  account_id INT NOT NULL REFERENCES account(id),
  -- The last time this refresh token was used to generate a new access token.
  -- Used for keeping track of how refresh tokens are used.
  last_used_at TIMESTAMP DEFAULT now(),
  -- The time at which a UUID was created. We should also consider adding extra
  -- information like the device this refresh token is attached to so that a
  -- person may sign out of their account on all their devices.
  created_at TIMESTAMP NOT NULL DEFAULT now()
);

-- NOTE: Users have full access to select, insert, update, and delete
-- refresh tokens since we want our API to use this access to authenticate
-- unauthorized users. This could be problematic, however, since it reveals
-- information like the last time a refresh token was used.
--
-- Currently this table is secured at the API level. Should we also consider
-- securing this table at the database level?
GRANT SELECT ON TABLE refresh_token TO connect_api;
GRANT INSERT ON TABLE refresh_token TO connect_api;
GRANT UPDATE ON TABLE refresh_token TO connect_api;
GRANT DELETE ON TABLE refresh_token TO connect_api;
